### ISSUE TITLE
🚀 [Feature] More embedded third party provider (LISTE ERSTELLEN!)

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection-Community/Human-Connection-New-20201003#2339]
> [<img alt="hermann-san" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/hermann-san) **Authored by [hermann-san](https://github.com/hermann-san)**
_<time datetime="2019-11-24T23:51:11Z" title="Monday, November 25th 2019, 12:51:11 am +01:00">Nov 25, 2019</time>_
_Closed <time datetime="2020-04-14T13:48:01Z" title="Tuesday, April 14th 2020, 3:48:01 pm +02:00">Apr 14, 2020</time>_
---

## :rocket: Feature
currently there is a number of embedded third-party provider like youtube that are supported, but some are not yet supported.  Particularly the screenshot tools like Greenshot, Shutter or ShareX support the below  image-provider and it would be useful to have those supported to make screenshot's visible in comments.  
Additionally it would be nice to have Pro/Contra discussions from Kialo embedded. This is a feature that was advertised in HC videos, etc. and I assume that people are looking for this feature but it's unclear when this will come in HC.  This would be an easy way to have HC-user use  this feature easily now  and get already some experience and idea on how to use it. 

[Kialo](https://support.kialo.com/hc/en-us/articles/360029527372-Embedding-Kialo-Discussions-on-Your-Website) Pro/Contra Discussion 

[Imgur](https://imgur.com/upload?beta)  (free and popular)
[Imageshak](http://www.imageshack.us/) (popular)
[Vgy.me](https://vgy.me/)  (also self-hosting)
[Chevereta](https://chevereto.com/) (also self-hosting)
[toilelibre](https://pix.toile-libre.org/)   looks like open source /not sure though 
[Pixelfeld](https://pixelfed.org/)

Audio:  [Funkwhale](https://funkwhale.audio/)  -   third party

Social Media :  Mastodon

**Comment by Tirokk** [comment]
> [<img alt="cypress[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2019-11-25T04:53:42Z" title="Monday, November 25th 2019, 5:53:42 am +01:00">Nov 25, 2019</time>_

---



<p align="center">
  <br />
  <img src="https://assets.cypress.io/github-pr-comment-icons/cypress-logo.png" height="32" />
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/2388/specs"><img src="https://assets.cypress.io/github-pr-comment-icons/green-check-mark.png" width="14" height="14" title="Passed" /></a> <b title="Passed">48</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/2388/failures"><img src="https://assets.cypress.io/github-pr-comment-icons/red-x.png" width="14" height="14" title="Failed" /></a> <b title="Failed">0</b>  &bull; <img src="https://assets.cypress.io/github-pr-comment-icons/gray-circle.png" width="14" height="14" title="Tests that did not run due to a developer annotating a test with .skip" /> <b title="Pending">0</b> &bull; <img src="https://assets.cypress.io/github-pr-comment-icons/yellow-triangle.png" width="14" height="14" title="Tests that did not run due to a failure in a mocha hook" /> <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | b27e3df79f |
| **Started** | Nov 26, 2019 11:26 AM |
| **Ended** | Nov 26, 2019 11:39 AM |
| **Duration** | 13:31 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 78 <img src="https://cdnjs.cloudflare.com/ajax/libs/browser-logos/48.0.4/chromium/chromium_32x32.png" width="16" height="16" /> |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/2388/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by hermann-san** [comment]
as a temporary workaround, services like flickr.com can be used for image uploads so that they can directly be seen in the comments of an article.
