### ISSUE TITLE
🐛 [Bug] Lokalise / translate all unlocalised Texts / Translations / Languages

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection-Community/Human-Connection-New-20201003#454]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-04-12T14:25:35Z" title="Friday, April 12th 2019, 4:25:35 pm +02:00">Apr 12, 2019</time>_
_Closed <time datetime="2019-08-23T14:26:27Z" title="Friday, August 23rd 2019, 4:26:27 pm +02:00">Aug 23, 2019</time>_
---

## Issue

In the Webapps are several texts not localised.

**Comment by Tititesouris** [comment]
Hello @Tirokk,

I am a native French speaker and I speak English fluently and German to a good level, so I would feel confident translating fr<->en, de->en and de->fr.
Am I right in assuming that I can simply edit the json files in Human-Connection-New-20201003/tree/234-fix/webapp/locales and submit a PR?
If so, I would be happy to have a look at them. I already spotted some common typos in the fr.json file
Also, as always when dealing with translations, context is very important. Is there a simple way to know where a translation key can be found in context, or should I simply ask here if I have a doubt?

Best regards,
Quentin

**Comment by Tirokk** [comment]
> [<img alt="ulfgebhardt" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-20T14:13:27Z" title="Saturday, April 20th 2019, 4:13:27 pm +02:00">Apr 20, 2019</time>_

---


This is more of an Issue then an Epic ;-)
